spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/custompcbuilder
    username: custompcuser
    password: custompcpass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect